add c_order_percent for chinese market fee
edtechre/pybroker pull request #61
Opened 2023-08-27 10:05 UTC by albertandking

Hi, Ed,
I have updated a new fee type for chinese stock market.
1. buy type should take at least 5 yuan
2. sell type should take 0.01 percent of amout stamp duty

2023-12-10 02:27 UTC, edtechre requested changes
The only blocking is clarification on:

"Does this extra fee apply to both selling a long order and when shorting a stock?"

Otherwise I can merge and make the rest of the changes. Thanks!

2023-12-10 02:27 UTC, edtechre commented on src/pybroker/portfolio.py
> +            if type == "buy":
The if/else is redundant here. You can remove the repeated section to make more readable:

fees = self._fee_amount / Decimal(100) * fill_price * shares
if fees < Decimal(5.0):
     fees = Decimal(5.0)
if type == "sell":
   fees = fees + Decimal(0.0001) * fill_price * shares

2023-12-10 02:27 UTC, edtechre commented on src/pybroker/portfolio.py
> +                fees = fees + Decimal(0.0001) * fill_price * shares
Does this extra fee apply to both selling a long order and when shorting a stock?

2023-12-10 02:27 UTC, edtechre commented on src/pybroker/portfolio.py
> +        fees = self._calculate_fees(fill_price, shares, type)
This needs unit tests but I will add these myself after I merge.

2023-12-10 02:27 UTC, edtechre commented on src/pybroker/common.py
> +    C_ORDER_PERCENT = "c_order_percent"
This needs documentation above.

2023-12-10 02:32 UTC, albertandking commented
> The only blocking is clarification on:
> 
> 
> 
> "Does this extra fee apply to both selling a long order and when shorting a stock?"
> 
> 
> 
> Otherwise I can merge and make the rest of the changes. Thanks!

Hello Ed, in the current Chinese market, you can only go long and not short, which means you can only sell stocks that you own. You cannot sell stocks that you do not own. Therefore, there are different settings for buying and selling.

2023-12-10 03:15 UTC, edtechre commented
Great, thank you for clarifying.

2023-12-10 03:16 UTC, edtechre approved these changes

2023-12-10 03:17 UTC, merged

2023-12-11 04:44 UTC, edtechre commented
Hi @albertandking,

I have another question:
> fees = fees + Decimal(0.0001) * fill_price * shares

Why is Decimal(0.0001) hardcoded? Is this guaranteed to be the case across all exchanges in China?

2023-12-11 05:53 UTC, edtechre commented
Note, a more scalable way of handling this would be to add support for setting a "FeeStructure" object that can implement custom fee logic. We could provide an implementation for the Chinese market (Shanghai stock exchange?)